# Input files
samples: ../resources/repadapt_trep_sample_sheet.txt
chromosomes: ../resources/chromosome_file.txt
bam_path: /node1nfs/archive/projects/trifolium/GLUE/dnaSeqQC_v2/results/bam
ref: /research/references/trifolium/repens/UTM_Trep_v1.0/UTM_Trep_v1.0_haploid_reference_softMasked.fasta
repadapt_prefix: rawg0003_trifolium_repens_santangelo  # Prefix added to beginning of all outputs

# Output
results_prefix: /scratch/projects/trifolium/repadapt_trep/results
log_prefix: /scratch/projects/trifolium/repadapt_trep/logs
